services:
    db:
        image: postgres:14
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - db-data:/var/lib/postgresql/data
    web:
        build: .
        command: gunicorn drf_api_permissions_postgres_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        
volumes:
    db-data:
